#! /usr/bin/env python3
# read (part of) the FA header
# and calculate the expected file size
# compare with actual file size
import sys
import os
fname = sys.argv[1]

# actual file size:
fs_actual = os.stat(fname).st_size
if fs_actual < 40 :
  print("File is much too small")

# from file header
f1 = open(fname, "rb")
f1.seek(0)
ssize = int.from_bytes(f1.read(8), byteorder='big')
f1.seek(32)
snum = int.from_bytes(f1.read(8), byteorder='big')
f1.close()
fs_expected = 8*ssize*snum

# compare 
# for debugging:
print("expected size:", fs_expected)
print("actual size:"  , fs_actual)

if fs_actual != fs_expected :
  print("File is not OK.")
else :
  print("OK")


